#!/usr/bin/env python3

import os
import datetime

date = datetime.datetime.now()

try:
    cpucmd = "cat /proc/loadavg"
    swapcmd = "free -m"
    memcmd = "free -m"
    usercmd = "users"
    diskcmd = "df -h > /tmp/tmp-disk-check"
    proccmd = "ps aux"
    ipcmd = "ip addr show enp2s0"

    print('\n')
    print('  System information as of ' + date.strftime("%c"))
    print('\n')

    #Calculates cpu usage
    def readcpu():
        cpuinfo = os.popen(cpucmd).readlines()
        cpuinfolist = cpuinfo[0].split()
        print("  System load       : " + cpuinfolist[0])

    def readswap():
        swapinfo = os.popen(swapcmd).readlines()
        for line in swapinfo:
            line2=line.split()
            if line2[0] == "Swap:":
                swapused = line2[2]
                swapavail = line2[1]

        swapusage = int(swapused)/int(swapavail)*100
        print("  Swap usage        : %" + str(round(swapusage, 1)))

    def readmem():
        meminfo = os.popen(memcmd).readlines()
        for line in meminfo:
            line2=line.split()
            if line2[0] == "Mem:":
                memused= line2[2]
                memavail= line2[1]

        memusage = int(memused)/int(memavail)*100
        
        print("  Memory Usage      : %" + str(round(memusage, 1)))
    
    def readusers():
        userinfo = os.popen(usercmd).readlines()
        print("  Users logged in   : " + str(len(userinfo)))

    # Calculates disk usage 
    def readdisk():
        os.system(diskcmd)

        path = '/tmp/tmp-disk-check'

        tmpfile = open(path, 'r')

        for line in tmpfile:
            line=line.split(' ')
            if line[0] == '/dev/sda2':
                rootline = [x for x in line if x] 
        print("  Usage of " + rootline[5][:-1] + "        : " + rootline[2] + "(" + rootline[4] + ") of " + rootline[1])

    def readproc():
        procinfo = os.popen(proccmd).readlines()
        print("  Processes         : " + str(len(procinfo)))

    def readip():
        ipinfo = os.popen(ipcmd).readlines()
        for line in ipinfo:
            line2 = line.split()
            if line2[0] == 'inet':
                ip = line2[1]
        print("  IP Address        : " + ip)
    
    def extra():
        print('\n')
except:
    print("Something didn't work! Please edit /etc/update-motd.d/60-sys-usage")


def main():
    readcpu()
    readmem()
    readswap()
    readusers()
    readdisk()
    readproc()
    readip()
    extra()

if __name__ == '__main__':
    main()

