#!/usr/bin/env python3

#-------------------------------------------------------------------------------
#-------------------------------------------------------------------------------
#
# Tyler(UnclassedPenguin) 60-sys-usage 2022
#
# Author: Tyler(UnclassedPenguin)
#    URL: https://unclassed.ca
# GitHub: https://github.com/UnclassedPenguin
#
#-------------------------------------------------------------------------------
#-------------------------------------------------------------------------------


import os
import datetime

date = datetime.datetime.now()

#Edit this line with the interface you want to show ip address.
interface='wlp5s0b1'

try:
    # These are the commands ran to find the different info
    cpucmd = "cat /proc/loadavg"
    swapcmd = "free -m"
    memcmd = "free -m"
    usercmd = "users"
    diskcmd = "df -h"
    proccmd = "ps aux"
    ipcmd = "ip addr show {}".format(interface)

    print('\n')
    print('  System information as of ' + date.strftime("%c"))
    print('\n')

    #Calculates cpu usage
    def readcpu():
        cpuinfo = os.popen(cpucmd).readlines()
        cpuinfolist = cpuinfo[0].split()
        print("  System load       : " + cpuinfolist[0])

    # Checks if there is swap and displays usage
    def readswap():
        try:
            swapinfo = os.popen(swapcmd).readlines()
            for line in swapinfo:
                line2=line.split()
                if line2[0] == "Swap:":
                    swapused = line2[2]
                    swapavail = line2[1]

            swapusage = int(swapused)/int(swapavail)*100
            print("  Swap usage        : " + str(round(swapusage, 1)) + "%")
        except:
            print("  Swap usage        : No swap found")

    # Calculates mem usage and displays as a percentage
    def readmem():
        meminfo = os.popen(memcmd).readlines()
        for line in meminfo:
            line2=line.split()
            if line2[0] == "Mem:":
                memused= line2[2]
                memavail= line2[1]

        memusage = int(memused)/int(memavail)*100
        
        print("  Memory Usage      : " + str(round(memusage, 1)) + "%")
    
    # Displays number of users logged in
    def readusers():
        userinfo = os.popen(usercmd).readlines()
        print("  Users logged in   : " + str(len(userinfo)))

    # Calculates disk usage for /
    def readdisk():
        diskinfo = os.popen(diskcmd).readlines()

        for line in diskinfo:
            line2=line.split()
            if line2[5] == "/":
                print("  Usage of " + line2[5] + "        : " + line2[2] + "(" + line2[4] + ") of " + line2[1])
                break

    # Displays number of processes running on system
    def readproc():
        procinfo = os.popen(proccmd).readlines()
        print("  Processes         : " + str(len(procinfo)))

    # Displays IP for interface set at top as "interface"
    def readip():
        ipinfo = os.popen(ipcmd).readlines()
        for line in ipinfo:
            line2 = line.split()
            if line2[0] == 'inet':
                ip = line2[1]
                break
        print("  IP Address        : " + ip)
    
    def extra():
        print('\n')
except:
    print("Something didn't work! Please edit /etc/update-motd.d/60-sys-usage")


def main():
    #Main program start
    readcpu()
    readmem()
    readswap()
    readusers()
    readdisk()
    readproc()
    readip()
    extra()

if __name__ == '__main__':
    main()

