#!/bin/bash

user=user
server=192.168.1.1
servername="server"
port=22

function fail {
  echo $1 >&2
  exit 1
}

function retry {
  local n=0
  local max=3
  local delay=1
  while true; do
    "$@" && break || {
      if [[ $n -lt $max ]]; then
        ((n++))
        echo "Connection failed. Attempt $n/$max:"
        sleep $delay;
      else
        fail "Connection failed after $n attempts."
      fi
    }
  done
}

if ping -q -c 1 -W 1 $server >/dev/null; then
  echo "Connecting to $servername..."
  retry ssh -o ConnectTimeout=5 $user@$server -p $port 
else
  echo "No IPv4 connection."
fi
