#!/bin/bash

#-------------------------------------------------------------------------------
#-------------------------------------------------------------------------------
#
# Tyler(UnclassedPenguin) Easy SSH 2022
#
# Author: Tyler(UnclassedPenguin)
#    URL: https://unclassed.ca
# GitHub: https://github.com/UnclassedPenguin
#
#-------------------------------------------------------------------------------
#-------------------------------------------------------------------------------

SCRIPTNAME="${0##*/}"
user="user"
server=192.168.1.1
servername="server"
port=22

Help() {
  echo "SSH to $servername"
  echo "Usage: $SCRIPTNAME [OPTIONS]"
  echo ""
  echo "Options:"
  echo " -h    : Print this help usage."
  echo " -p    : Ping the server"
  echo " -i    : Get info on server"
}

Info() {
  echo "Info for $servername"
  echo "  IP: $server"
  echo "Port: $port"
}

Pingserver() {
  echo "Pinging $servername..."
  ping $server
}

Test() {
  echo "this is a test"
}

optspec=":hipt:"
while getopts "$optspec" option; do
  case $option in
    h)
      Help
      exit;;
    i)
      Info
      exit;;
    p)
      Pingserver
      exit;;
    t)
      Test
      exit;;
  esac
done

function fail {
  echo $1 >&2
  exit 1
}

function retry {
  local n=0
  local max=3
  local delay=1
  while true; do
    "$@" && break || {
      if [[ $n -lt $max ]]; then
        ((n++))
        echo "Connection failed. Attempt $n/$max:"
        sleep $delay;
      else
        fail "Connection failed after $n attempts."
      fi
    }
  done
}

if ping -q -c 1 -W 1 $server >/dev/null; then
  echo "Connecting to $servername..."
  retry ssh -o ConnectTimeout=5 $user@$server -p $port
else
  echo "No IPv4 connection."
fi
